### ISSUE TITLE
v4.2 does not start

### ISSUE THREAD

**Issue by NooB9496** [ledoge/novideo_srgb#90]
**I have .NET Framework 4.8.1 installed
Windows 11 Home
23H2
build number 22631.3155
Nvidia Driver Version 551.61**

**Event: 1000, Application Error**

Faulting application name: novideo_srgb.exe, version: 1.0.0.0, timestamp: 0xc0670bf5
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3155, timestamp: 0x8c2ee5db
Exception code: 0xe0434352
Error offset: 0x0000000000065b0c
Faulting process ID: 0x0x18C4
The time the faulty application started: 0x0x1DA6CDCE125B46E
Faulting application path: C:\Users\Pest\Downloads\JDownloader\novideo_srgb.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 78abaea6-81bc-4ec9-9337-8de75e864214
Full name of the causing package:
Application ID relative to the offending package:

**Event: 1026, .NET Runtime**

Application: novideo_srgb.exe
Architecture version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception information: NvAPIWrapper.Native.Exceptions.NVIDIAApiException
    in NvAPIWrapper.Native.DisplayApi.EnumNvidiaDisplayHandle()
    in NvAPIWrapper.Display.Display.GetDisplays()
    in novideo_srgb.MainViewModel.UpdateMonitors()

Exception information: System.Windows.Markup.XamlParseException
    at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
    at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
    at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
    at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
    at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
    in System.Windows.Application.DoStartup()
    at System.Windows.Application.<.ctor>b__1_0(System.Object)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
    at System.Windows.Threading.DispatcherOperation.Invoke()
    at System.Windows.Threading.Dispatcher.ProcessQueue()
    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
    in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
    in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
    in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
    in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
    at System.Windows.Application.RunDispatcher(System.Object)
    at System.Windows.Application.RunInternal(System.Windows.Window)
    in novideo_srgb.App.Main()

**Comment by Ofcmnt2** [comment]
I have this issue too, both with 4.1 and 4.2-fix. It's only happening on my laptop (**nvidia driver 551.61**) with only the internal display, and does not happen on my desktop (**nvidia driver 551.76**) with two displays (one DP, one HDMI input).

**Windows version is the same on both machines,
23H2
22631.3296**

**Error logs from laptop as follows:**

**Event 1000, Application Error**

Faulting application name: novideo_srgb.exe, version: 1.0.0.0, time stamp: 0xe4e908ea
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3235, time stamp: 0x2b72307b
Exception code: 0xe0434352
Fault offset: 0x0000000000065b0c
Faulting process id: 0x0xCA8
Faulting application start time: 0x0x1DA79827987E8D4
Faulting application path: C:\Applications\novideo-srgb\novideo_srgb.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9a6d5f62-3d83-44cc-b918-038602e407f4
Faulting package full name: 
Faulting package-relative application ID: 

**Event: 1026, .NET Runtime**

Application: novideo_srgb.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: NvAPIWrapper.Native.Exceptions.NVIDIAApiException
   at NvAPIWrapper.Native.DisplayApi.EnumNvidiaDisplayHandle()
   at NvAPIWrapper.Display.Display.GetDisplays()
   at novideo_srgb.MainViewModel.UpdateMonitors()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at novideo_srgb.App.Main()

**Comment by frnksmdlkedjnfr** [comment]
same problem here
